const PUZZLES = [
  ["FAITH", "PARTY"],
  ["LIGHT", "NIGHT", "MIGHT", "RIGHT"],
  ["CARTS", "HARTS", "PANTS"],
  ["STYLE", "SHINE"],
  ["EPOCH", "SPICY"],
  ["MACHO", "NACHO", "YACHT"],
  ["TRICK", "THING"],
  ["KNOBS", "KNIFE"],
  ["WRONG", "WHOLE"],
  ["HEROS", "HARPS"],
  ["PORCH", "PARCH"],
  ["CATER", "NAVEL"],
  ["VOCAL", "NOMAD"],
  ["ALIEN", "ASPEN"],
  ["VALUE", "WALTZ"],
  ["CHAIN", "CHOKE"],
  ["CHORE", "ALURE"],
  ["SMOKE", "SMART"],
  ["QUAIL", "TRAIN"],
  ["AISLE", "RISKY"],
  ["BREAK", "BREAD", "BROAD"],
  ["BOARD", "HOARD", "BEARD"],
  ["MOUND", "ROUND", "FOUND", "POUND"],
  ["HONEY", "NOSEY", "MONEY"],
  ["STAIN", "STALK", "STAIR"],
  ["SNORE", "SCORE", "STORE", "SHORE"],
  ["PALET", "VALET", "CADET"],
  ["TOAST", "ROAST", "COAST", "BOAST"],
  ["SWIPE", "SLOPE", "SCOPE"],
  ["STAKE", "SLAKE", "SNAKE", "SHAKE"],
  ["BLAME", "BLAZE", "BLOKE"],
  ["NIGHT", "MIGHT", "RIGHT", "LIGHT"],
  ["COVER", "HOVER", "MOVER", "ROVER"],
  ["ADOBE", "ADORE", "ABOPT"],
  ["FALSE", "CAUSE", "PAUSE"],
  ["CHAMP", "CHUMP", "CHIME"],
  ["BRINK", "BRING", "BRIDE"],
];